### ISSUE TITLE
[Module Addition] QR Code Reader/Generator

### ISSUE THREAD

**Issue by pratyushtiwary** [pratyushtiwary/devty#26]
The requested module will be able to generate and read QR codes. Reference: https://devutils.com/demo/#qrcode

**Comment by josediego** [comment]
Hello, can I be assigned this task?

**Comment by josediego** [comment]
I have the PR ready to roll, but I was wondering... can we wait until October to make it count on the Hackoctober event, please?

**Comment by pratyushtiwary** [comment]
Ok, until then makybe

**Comment by pratyushtiwary** [comment]
Sure. Until then maybe document the code so that when you submit the PR it'll be easy for me to go through it.

**Comment by josediego** [comment]
Absolutely, I'll start documenting the code using JSDoc format :) 

Here's an overview of the new module's appearance:

<img width="1696" alt="image" src="https://github.com/pratyushtiwary/devty/assets/5665920/a3ee7658-9787-4e80-a016-0fae6ddb28bf">

Additionally, you can upload a QR code to extract text from it:

<img width="1696" alt="image" src="https://github.com/pratyushtiwary/devty/assets/5665920/3bb79c33-e17b-4357-86d2-a9de6cb88831">
<img width="1696" alt="image" src="https://github.com/pratyushtiwary/devty/assets/5665920/347ea94b-719f-499b-ac48-6e4c4aa4f075">

When no QR code is detected in the uploaded image, we display an error message like this:

<img width="1696" alt="image" src="https://github.com/pratyushtiwary/devty/assets/5665920/5dde41f0-7c65-47aa-b120-19eb394b3251">

Lastly, we offer a variety of QR templates:
<p align="center">
<img width="416" alt="image" src="https://github.com/pratyushtiwary/devty/assets/5665920/8dfbba67-a652-4588-9739-58d7ebbcb472">
</p>

Please let me know if this feature covers all the required functionality for this new module

**Comment by pratyushtiwary** [comment]
This looks amazing! Well done @josediego

You've covered all the functionalities that I expected, thank you so much for the amazing work.


Also I've gone through your code and it looks good the only thing that bothers me is `watchEffect` usage, if possible then please don't use `watchEffect`, it makes the module slow.

**Comment by josediego** [comment]
Thanks for the suggestion @pratyushtiwary 

I removed the dependency of `watchEffect` and it works fine now :) check this out https://github.com/josediego/devty/commit/8090ceea188044e71f725eadf25d417ccff2c488

**Comment by pratyushtiwary** [comment]
Great work!
